### ISSUE TITLE
Bug and Feature Request : Problem with Rich Text editor

### ISSUE THREAD

**Issue by ramesh-dada** [the-turk/flarum-mathren#29]
### Bug Report

Bug : When I click on mathren icon on composer toolbar nothing happens and in console I can see this error.
![image](https://user-images.githubusercontent.com/75124237/130813350-c29a3474-70f2-4df3-bb81-0a09189a6935.png)

Expected behavior: It should show dropdown as it shows in normal composer that asks for inline or block maths.

***

### Feature Request 

Askvortsov Rich text editor support something like:
![Demo](https://user-images.githubusercontent.com/75124237/130814936-2f15d5ef-4387-4c08-910f-61b5b6f4dfac.gif)

**Comment by hasan-ozbey** [comment]
This might be an issue with another extension 'cause nobody can reproduce this but you. So confirm that if this is an MathRen issue.

As for your feature request, this extension was made for plain LaTeX users and doesn't provide any of WYSIWYG functions. If WYSIWYG is what you're looking for, then go with the "Rich Text Editor" extension.

**Comment by ramesh-dada** [comment]
Yes this is an issue that happens with Rich Text editor only not with default composer.

**Comment by the-turk** [comment]
Maybe I should mark this incompatible with that. Using these two together doesn't make any sense.
