### ISSUE TITLE
Conflict with flarum/bbcode

### ISSUE THREAD

**Issue by suflaj** [the-turk/flarum-mathren#30]
This extension has a conflict with `flarum/bbcode`. The rendering becomes screwed no matter what you use to define a latex chunk - both bbcode and aliases fail. This is how it looks like:

![image](https://user-images.githubusercontent.com/77863921/135782092-30c57c73-e424-4052-baf4-3a08ea5a12bc.png)

When you disable the `flarum/bbcode` extension, this is how it looks like:

![image](https://user-images.githubusercontent.com/77863921/135782220-4204d867-1118-4149-aa79-71152c011424.png)

This was observed both on `beta.13`, and on `1.0.4`, now that I've upgraded.

**Comment by suflaj** [comment]
I've just encountered something even weirder. Apparently the extension stopped working by itself again. But BBCode was off. So I turned it on again, and latex started rendering again.

What gives???

**Comment by hasan-ozbey** [comment]
No, it doesn't conflict with BBCode, it's almost impossible. You've got an another issue going on there, check your console log for errors/warnings etc. Maybe it's your browser? Or maybe a cache issue? Or CDN? Looks like the KaTeX script is not loading as it should be.

And don't switch between major versions, 1.0 introduced a new way of rendering things so some tex might not be rendered if you wrote them while using 0.x - just stay in 1.0.

**Comment by suflaj** [comment]
I'm not saying that there is an actual error with it - console logs are empty, logs are empty. What I'm saying is that it's likely that parsing priorities are messed up, although now I think it might be a cache error (even though I've cleared Flarum's cache multiple times).

Anyways, you might close it for now because the issue doesn't persist, unless you can reproduce it. Unfortunately I cannot give you my backup to check it out yourself - but it happened after I upgraded from beta.13 to beta.16 directly, and then to 1.0.4. It's not a problem of me needing to reload the post - latex stays latex.

I will comment on this if it reappears, though, with more info. But from the first time, I couldn't find anything but the conflict with BBCode as described. PERHAPS it's due to ordering - BBCode was activated before MathRen, now it's the opposite - I'll test this out in the next update of my forum and let you know.

**Comment by hasan-ozbey** [comment]
Oh I think I get it now, upgrading from 0.x to 1.x causes this issue. You need to update (edit & save) posts those contains TeX from earlier version of the extension (0.x), manually, one by one. That's because old posts must be stored in new format to get proper rendering. Sorry for the inconvenience. This was an outcome of alias delimiters feature, introduced in 1.x. It won't happen again.

**Comment by suflaj** [comment]
I keep telling you, this is not the case. This exact problem happened when I was on 0.3 and beta.13. It happened after I had to disable the extension because a user created an equation that crashed the frontend, and after I put that in code quotes and re-enabled the extension, it could no longer render things. I didn't investigate much then because I saw on discuss there were some issues with the new version, and we were updating in a few days so I ignored it until then.

Now, when updated, I didn't change any of the latex posts. I changed perhaps one because I was checking if I have to do that, but it didn't make a difference. Only enabling and disabling the BBCode extension changed something.

Now, it might be something trivial, it might be something avoided by this new formatting - point is, the BBCode extension might have intervened in the rendering for some reason and you need to be aware of it. Because that formatting looks like MathRen was disabled specifically for the tags (i used math and imath), not like it was partially working or like it crashed. And, again, this initially happened on 0.3, so it likely has nothing to do with 1.0

**Comment by hasan-ozbey** [comment]
Alright, strange it is. Looks like nothing I can do to help you as myself and some other users can't reproduce the issue. I'll keep this in my mind. Feel free to re-open the issue if it happens again.

---
As a side note here, the BBCode extension doesn't really 'activates' the BBCode feature in your forum. BBCodes are always there, that extension just defines some basic tags like bold, italic etc. to make them available in the forum. The MathRen also defines its own tags and it has nothing to do with the BBCode extension. They shouldn't affect each other.
