### ISSUE TITLE
It doesn't works well

### ISSUE THREAD

**Issue by SwaggyMacro** [the-turk/flarum-mathren#32]
![image](https://user-images.githubusercontent.com/38845682/160221279-6e3db49a-688e-496b-b52f-038326f8c350.png)
it's only working when I'm editing. 
And, if I post it, then...
![image](https://user-images.githubusercontent.com/38845682/160221400-c15c5553-4c48-415e-8df1-8320045a6a78.png)

**Comment by hasan-ozbey** [comment]
Please look out for errors in your browser's console, this might be a confliction with another extension. I need more details.

**Comment by SwaggyMacro** [comment]
> Please look out for errors in your browser's console, this might be a confliction with another extension. I need more details.

You reminded me. I found the problem.
MathRen conflicts with hashtag.

**Comment by SwaggyMacro** [comment]
![image](https://user-images.githubusercontent.com/38845682/160762031-ffa4ea06-821a-4a8a-bf25-057fcab62ce1.png)
it works now.

**Comment by SwaggyMacro** [comment]
> Please look out for errors in your browser's console, this might be a confliction with another extension. I need more details.

thank you for your work!!!

**Comment by SwaggyMacro** [comment]
but, is there any solution for work with hashtag?

**Comment by SwaggyMacro** [comment]
if u install mathren first, the mathren will works well, but hashtag wont, and vice versa.
